#!/usr/bin/env bash

sudo="$(command -v sudo)"
SUDO="$sudo"

if [[ -n "$BBX_DEBUG" ]]; then
  set -x
fi

os_type() {
  case "$(uname -s)" in
    Darwin*) echo "macOS";;
    Linux*)  echo "Linux";;
    MING*)   echo "win";;
    *)       echo "unknown";;
  esac
}

if [[ -z "$1" ]]; then
  echo "Supply a domain name as first argument" >&2
  exit 1
fi

echo "Using mkcert for certificate generation" >&2

if ! command -v jq &>/dev/null; then
  if [ "$(os_type)" == "macOS" ]; then
    brew install jq
  else
    $sudo $APT install -y jq 2>/dev/null || true
  fi
fi

hostname="$1"
amd64=""

if ! command -v mkcert &>/dev/null; then
  if [ "$(os_type)" == "macOS" ]; then
    brew install nss mkcert
  elif [ "$(os_type)" == "win" ]; then
    choco install mkcert || scoop bucket add extras && scoop install mkcert
  else
    amd64=$(dpkg --print-architecture || uname -m)
    $SUDO $APT install -y libnss3-tools 2>/dev/null || true
    curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/$amd64"
    chmod +x mkcert-v*-linux-$amd64
    $SUDO cp mkcert-v*-linux-$amd64 /usr/local/bin/mkcert
    rm mkcert-v*
  fi
fi

mkcert -install

if [[ ! -f "$HOME/sslcerts/privkey.pem" || ! -f "$HOME/sslcerts/fullchain.pem" ]]; then
  :
else
  echo "IMPORTANT: sslcerts already exist in $HOME/sslcerts directory. We ARE overwriting them."
fi

mkdir -p "$HOME/sslcerts"
pwd=$(pwd)
cd "$HOME/sslcerts"
mkcert --cert-file fullchain.pem --key-file privkey.pem $1 localhost 127.0.0.1
cd "$pwd"

mkdir -p "$HOME/sslcerts"
if [[ -f ./cp_certs ]]; then
  $sudo -u root ./cp_certs "$1" "$HOME/sslcerts/"
elif [[ -f ./deploy-scripts/cp_certs ]]; then
  $sudo -u root ./deploy-scripts/cp_certs "$1" "$HOME/sslcerts/"
else
  $sudo -u root bash -c "bash <(curl -s https://raw.githubusercontent.com/BrowserBox/BrowserBox/main/deploy-scripts/cp_certs) \"$1\" \"$HOME/sslcerts/\""
fi
GROUP="$(id -gn || echo "$USER")"
$sudo chown "${USER}:${GROUP}" "$HOME/sslcerts/"*
chmod 600 "$HOME/sslcerts/"*
